categories:
  - 
    label: breaking
    title: Breaking
  - 
    label: feature
    title: New
  - 
    label: bug
    title: "Bug Fixes"
  - 
    label: dependencies
    title: "Dependency Updates"
  -
    label: security
    title: Security
name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
template: |
    # Changes
    $CHANGES
version-resolver: 
  major: 
    labels: 
      - breaking
      - major
  minor: 
    labels: 
      - feature
      - minor
  patch: 
    labels: 
      - bug
      - dependencies
      - security
      - patch
  default: patch