version: '3'

services:
  redis:
    image: redis:latest
    expose:
      - '6379/tcp'
    networks:
      - main

  mongo:
    image: mongo:6
    expose:
      - '27017/tcp'
    networks:
      - main

  django-q2:
    build:
      dockerfile: ./Dockerfile.dev
      context: .
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongo
    networks:
      - main

networks:
  main:
