# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0008_auto_20160224_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='seconds',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of seconds for the Seconds type', null=True),
        ),
        # TODO: populate new field with `minutes * 60`
        migrations.RemoveField(
            model_name='schedule',
            name='minutes',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[(b'O', 'Once'), (b'I', 'Seconds'), (b'H', 'Hourly'), (b'D', 'Daily'), (b'W', 'Weekly'), (b'M', 'Monthly'), (b'Q', 'Quarterly'), (b'Y', 'Yearly')], default=b'O', max_length=1, verbose_name='Schedule Type'),
        ),
    ]
