# Generated by Django 2.2.5 on 2019-10-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0009_auto_20171009_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='from_registry',
            field=models.BooleanField(default=False),
        ),
    ]
